# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(default='image/defult.png', max_length=500, verbose_name='image'),
            preserve_default=False,
        ),
    ]
